[package]
name = "vm-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "4.5.18", features = ["derive"] }
